python3 imageConvert.py alien1.jpeg ..\build\alien1.bin
python3 imageConvert.py boy1.jpeg ..\build\boy1.bin
python3 imageConvert.py boy2.jpeg ..\build\boy2.bin
python3 imageConvert.py boy3.jpeg ..\build\boy3.bin
python3 imageConvert.py elf1.jpeg ..\build\elf1.bin
python3 imageConvert.py girl2.jpeg ..\build\girl2.bin
python3 imageConvert.py girl3.jpeg ..\build\girl3.bin
python3 imageConvert.py monster.jpeg ..\build\monster.bin
python3 imageConvert.py ogre.jpeg ..\build\ogre.bin
python3 imageConvert.py wizard.jpeg ..\build\wizard.bin
python3 imageConvert.py woman.jpeg ..\build\woman.bin
